### PR TITLE
Update react-native peerDependencies to 0.59.9

### PR DESCRIPTION
**Pull request by kwokhou**

### CODE REVIEW

**Comment by mribbons** [comment]
Hi @kwokhou, 
Thanks for the PR. Would you be ok with RN "react-native": "^0.59.9"? 

This version is required to produce a proper 64 bit version, which is required to meet new play store requirements.

https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

https://github.com/facebook/react-native/issues/2814#issuecomment-457688789

**Comment by kwokhou** [comment]
hi @mribbons, Yes. that is fine.

**Comment by mribbons** [comment]
Hi @kwokhou,
Would you kindly mind updating to "react-native": "^0.59.9" and making sure everything compiles, then push to this branch?

I don't have time to test at the moment.

Thanks.

**Comment by kwokhou** [comment]
Ok done. I compiled using Android Studio. No error.
android studio

**Comment by mribbons** [comment]
Thanks @kwokhou  just FYI that compiling in Android Studio isn't a good test of changing the peerDependences as it doesn't use package.json.

I have created a fresh react-native project @0.55.9 and confirmed everything works.

Will merge now and push a new npm version soon.

**Pull request merged**
